SOCIAL_AUTH_TWITTER_KEY = 'YJ0zfFjkBdo7w7V9d6uXFYcfJ'
SOCIAL_AUTH_TWITTER_SECRET = '47JzqcKdBsTpy79XeSMBAR1kzWkNL9RsP8ocQb7EHwhXksh3eV'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'
